### PR TITLE
Git hub page

### PR DESCRIPTION
**Pull request by YMikita**

### CODE REVIEW

**Comment by izlotin** [comment]
As far as I can see lot of core files were deleted. What is the purpose?

**Comment by YMikita** [comment]
> 

GQW#

**Comment by YMikita** [comment]
> As far as I can see lot of core files were deleted. What is the purpose?

The GitHub page doesn't need these files.
In this branch shouldn't be other files that are not related to GitHub Pages.
We only use this branch to display the GitHub page.

**Comment by izlotin** [comment]
> 

Thats OK then

**Pull request closed without merging**
